### ISSUE TITLE
Scoped packages conflict with non-scoped packages

### ISSUE THREAD

**Issue by robwormald** [mjackson/npm-http-server#13]
This one drove me a little nuts locally for a while.

RxJS publishes (long story) in parallel to `@reactivex/rxjs` and `rxjs` - these end up shadowing each other in the tmp directory.

**Comment by mjackson** [comment]
We currently [use `@scope/package-version` as the tmp directory name](https://github.com/mjackson/npm-http-server/blob/2051575d93b976f07eeb0a077754fb0b7d70ace0/modules/serveNPMPackageFile.js#L43). Wouldn't that create two separate directories?

**Comment by kentcdodds** [comment]
What about using [tmp](https://www.npmjs.com/package/tmp) to create temporary directories?

**Comment by mjackson** [comment]
The idea behind the approach we're taking now is that we can use the tmp directory as a local cache so we don't have to download stuff from the registry every time a request is made. This really speeds things up when you're testing stuff locally or using a client that doesn't respect the long-lived HTTP caching headers (e.g. anything that isn't a browser, like curl).

**Comment by kentcdodds** [comment]
Ah, I see. Thanks for explaining
