### ISSUE TITLE
Should the repo be cloned or npm install-ed?

### ISSUE THREAD

**Issue by mattdsteele** [mjackson/npm-http-server#22]
Installing the module from npm as the `README` states, I can't get the project to run; there's no `bin` or `main` function I can call, and trying to `require('npm-http-server/server');` appears to load the non-Babel-ed code so it fails on `import` syntax.

It looks like the way that works is to clone the repo and run `npm start` - is this intentional? If so, is there a reason the module was published to npm?

Happy to submit any PRs to get docs in sync; I'm really looking forward to getting this up & running!

**Comment by mjackson** [comment]
> is there a reason the module was published to npm?

That's a great question. I can't think of any reason right now, other than the fact that you might want to use some of the express middleware we provide to create your own server. But even then you'd still need to transpile the code in `modules`.

But ya, the way to get it working now is to clone and follow the instructions in the README.

**Comment by mjackson** [comment]
I should also note that it's my intention to eventually get all npmcdn-specific stuff (like the `public` dir) OUT of this repo and make it a proper standalone package. Just a bit time-constrained, atm.
