### ISSUE TITLE
Wrap CommonJS into browser-compatible code.

### ISSUE THREAD

**Issue by just-boris** [mjackson/npm-http-server#24]
As I understand the `npmcdn` is intended to be as a provider of npm-modules for browsers. But usually npm-modules designed to work in CommonJS environment, which browsers haven't. So, there is need to do extra actions to make them work in browser like webpack does.

Now when I want to add `history` module to a [JSFiddle](https://jsfiddle.net/y3xtmrhm/), I am just getting  `Uncaught ReferenceError: exports is not defined`

Do you have any concern or plans about this?

**Comment by kentcdodds** [comment]
For your use case, you want to get the built file that's published to the registry: https://npmcdn.com/history@1.12.5/umd/History.min.js

What you're looking for is in the roadmap though :-)

**Comment by just-boris** [comment]
@kentcdodds thanks for pointing this in the `history`. But not every module has an `umd` folder.

Good to hear that this is in the roadmap. Where can I look at it and maybe participate, if I can do something for it?

**Comment by rtorr** [comment]
hey @just-boris,

I have been working on this, but its been slow moving due to work/life priorities. I have a working prototype here https://github.com/rtorr/jsbundler, and discussion has started here https://github.com/mjackson/npm-http-server/pull/10

Feel free to chime in or help :D

**Comment by just-boris** [comment]
@rtorr great, jsbundler really does the thing!

**Comment by bclinkinbeard** [comment]
FWIW, wzrd.in already supports this. Might be worth looking at their implementation. https://github.com/jfhbrook/wzrd.in/blob/master/singular.js#L9

**Comment by kentcdodds** [comment]
Anyone know any reason what the heck [this line](https://github.com/jfhbrook/wzrd.in/blob/master/singular.js#L29) is for? I'm not intending to turn this into a bash on that code or anything. Just a sanity check that this is not necessary or maybe it's doing something I'm not familiar with...

**Comment by rtorr** [comment]
@bclinkinbeard I think it would be a good idea to use existing code. Does look like it fails on peer deps https://wzrd.in/standalone/react-router@latest

**Comment by nkbt** [comment]
@kentcdodds it's an old slow but working way of cloning an object =). Fails hard on recursive structures.

**Comment by kentcdodds** [comment]
Ah, makes sense. Thanks @nkbt. Sorry to divert conversation. Carry on!

**Comment by mjackson** [comment]
I agree this would be very useful! This is a dup of #3. Let's talk about it over there.
