### ISSUE TITLE
Generate bundles using ?bundle query param

### ISSUE THREAD

**Issue by mjackson** [mjackson/npm-http-server#3]
Let's introduce a `?bundle` query parameter that instructs the server to build a bundle for us using webpack. Since webpack can potentially emit many files in a bundle, we'll need to have a special directory we can use to store the bundle for future requests. For now, we can just generate the build into a `*-bundle` directory that lives next to the decompressed tarball on disk. So, for example, our tmp dir file hierarchy will look like:

```
tmp
├── expect-1.12.0
├── expect-1.12.0-bundle
├── history-1.12.4
├── history-1.12.4-bundle
└── history-1.12.5
```

**Comment by rtorr** [comment]
Not exactly as described, but needs feedback nonetheless. And add some more of the stuff we talked about.

https://github.com/mjackson/npm-http-server/pull/25

**Comment by mjackson** [comment]
After thinking about this for a long, long time, I'm not convinced it's terribly useful. Services like wzrd.in and brcdn.org already do this, but they're not terribly popular. Let's hold off on this for now.
