### ISSUE TITLE
Deal with bower?

### ISSUE THREAD

**Issue by kentcdodds** [mjackson/npm-http-server#6]
I don't know if this is something we really need to think about, but if we're hoping to make npmcdn.com really eliminate the need for bower I think this could be handy...

If you do this: `bower install https://npmcdn.com/lodash` it totally works, but what gets saved to disk is this:

```
~/Desktop/tmp
🚀  $ tree .
.
├── bower.json
└── bower_components
    └── lodash
        └── index

2 directories, 2 files
```

The resulting file is simply called `index` with no extension at all. If you have a version on it: `bower install https://npmcdn.com/lodash@3.9.3` then you get:

```
~/Desktop/tmp
🚀  $ tree .
.
├── bower.json
└── bower_components
    └── lodash@3.9
        └── index.3

2 directories, 2 files
```

Which is quite odd I think, and even though technically it should still work fine, I wouldn't be surprised if issues cropped up when people commit their `bower_components` directory and deploy that and then their server doesn't know what headers to set because the file extension is wrong.

Basically what needs to happen is the url that bower is curling needs to end in the desired extension. However we can't just simply allow for `https://npmcdn.com/lodash@3.9.3.js` accross the board because then we'd need `https://npmcdn.com/lodash.js` and there are some packages that have `.js` in the name ([for example](https://www.npmjs.com/package/is.js)).

So I'm not certain of the best approach, but the more straightforward the better I think... I like the idea of allowing you to grab any file in the package as we have now, so I don't think we should change that behavior, but we need to come up with a way of allowing the last `/` URL part to be the desired name of the file.

## Skip to the next header...

So what if we had a query param to indicate that the last `/` URL part shouldn't be part of the file search but should actually part of the name? Something like this:

```
https://npmcdn.com/bootstrap@3.3.5/dist/css/bootstrap.css/whatever-i-want.css?lastIsFilename=true
https://npmcdn.com/bootstrap@3.3.5/dist/js/bootstrap.js/whatever-i-want.js?lastIsFilename=true
```

:point_up_2: contrived example... Bootstrap would actually work out alright in this case...

I'm not wild about the `lastIsFilename` query param name, but I think you get the idea. This would result in bower downloading with something like this:

## Skip to here

Turns out that some of my assumptions were wrong. Given this kind of `bower.json`:

```javascript
"dependencies": {
  "bootstrap.css": "https://npmcdn.com/bootstrap@3.3.5/dist/css/bootstrap.css",
  "bootstrap.js": "https://npmcdn.com/bootstrap@3.3.5/dist/js/bootstrap.js"
}
```

That results in this file structure

```
~/Desktop/tmp
🚀  $ tree .
.
├── bower.json
└── bower_components
    ├── bootstrap.css
    │   └── index.css
    └── bootstrap.js
        └── index.js

3 directories, 3 files
```

:-( Meaning that bower isn't using just the last filename and using that... But it *is* using the extension for the extension of `index` which pretty much solves the issue anyway. So basically all that needs to happen is the URL needs to be able to end in the extension of your choice... What do you think we could do to make that happen?

**Comment by nkbt** [comment]
See https://github.com/nkbt/react-component-template/blob/master/scripts/bower-version.js

Bower supports zip files well.

**Comment by nkbt** [comment]
I guess this can be added to npmcdn itself... I will have a look and PR when it's ready

**Comment by nkbt** [comment]
Created PR #17

**Comment by kentcdodds** [comment]
Thanks! I hope it gets merged!
